/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

//register address
typedef volatile unsigned int vint32_t;

//Register Address
//RCC
#define RCC_BASE	0x40021000
#define RCC_APB2ENR	*(volatile uint32_t *) (RCC_BASE + 0x18)
#define RCC_IOPAEN	(1<<2)


//GPIO
#define GPIOA_BASE	0x40010800
#define GPIO_CRH	*(volatile uint32_t *) (GPIOA_BASE + 0x04)
#define GPIO_CRL	*(volatile uint32_t *) (GPIOA_BASE + 0x00)
#define GPIOA_ODR	*(volatile uint32_t *) (GPIOA_BASE + 0x0C)
#define GPIOA13		(1UL<<13)

//EXTI
#define EXTI_BASE	0x40010400
#define EXTI_IMR	*(volatile uint32_t *) (EXTI_BASE + 0x00)
#define EXTI_RTSR	*(volatile uint32_t *) (EXTI_BASE + 0x08)
#define EXTI_PR		*(volatile uint32_t *) (EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE	0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *) (AFIO_BASE + 0x08)

#define NVIC_EXTIE0	*(volatile uint32_t *) (0xE000E100)
void Clock_Init()
{
	//Enable Clock GPIOA
	RCC_APB2ENR |= RCC_IOPAEN;

	//Enable Clock AFIOEN
	RCC_APB2ENR |= (1<<0);

}
void GPIOA_Init()
{
	//Pin13 port A output
	GPIO_CRH &= 0xff0fffff;
	GPIO_CRH |= 0x00200000;

	//PinA 0 input floating
	GPIO_CRL |= (1<<2);
}
int main(void)
{
	Clock_Init();
	GPIOA_Init();

	//EXTI x configuration (x=0) to PORTA0
	AFIO_EXTICR1 = 0;

	//Enable Rising Trigger
	EXTI_RTSR |= (1<<0);
	//Enable EXTI0 Line 0 (Mask 1)
	EXTI_IMR |= (1<<0);

	//Enable NVIC Irq6  <<>> EXTI0
	NVIC_EXTIE0 |= (1<<6);
	while(1);

	return 0;
}

void EXTI0_IRQHandler(void)
{
	//IRG is triggered EXTI0 >> PORTA Pin 0 _|- Rising Edge
	//toggle led pin A 13
	GPIOA_ODR ^= (1<<13);

	//clear Pending Request for line 0
	EXTI_PR |= (1<<0);
}

