/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
typedef volatile unsigned int vint32_t;



#define RCC_BASE	0x40021000

#define RCC_APB2ENR	*(volatile uint32_t *) (RCC_BASE + 0x18)
#define RCC_IOPAEN	(1<<2)
#define RCC_IOPBEN	(1<<3)

#define RCC_CR		*(vint32_t*) (RCC_BASE+0x0)
#define RCC_CFGR	*(vint32_t*) (RCC_BASE+0x04)
#define RCC_AHBRSTR	*(vint32_t*) (RCC_BASE+0x28)






#define GPIOA_BASE	0x40010800
#define GPIOB_BASE	0x40010C00

#define GPIOA_CRL	*(vint32_t*) (GPIOA_BASE + 0x00)
#define GPIOA_CRH	*(vint32_t*) (GPIOA_BASE + 0x04)
#define GPIOA_IDR	*(vint32_t*) (GPIOA_BASE + 0x08)
#define GPIOA_BSRR	*(vint32_t*) (GPIOA_BASE + 0x10)
#define GPIOA_BSRR	*(vint32_t*) (GPIOA_BASE + 0x10)
#define GPIOA_BRR	*(vint32_t*) (GPIOA_BASE + 0x14)
#define GPIOA_LCKR	*(vint32_t*) (GPIOA_BASE + 0x18)

#define GPIOB_CRL	*(vint32_t*) (GPIOB_BASE + 0x00)
#define GPIOB_CRH	*(vint32_t*) (GPIOB_BASE + 0x04)
#define GPIOB_IDR	*(vint32_t*) (GPIOB_BASE + 0x08)
#define GPIOB_BSRR	*(vint32_t*) (GPIOB_BASE + 0x10)
#define GPIOB_BSRR	*(vint32_t*) (GPIOB_BASE + 0x10)
#define GPIOB_BRR	*(vint32_t*) (GPIOB_BASE + 0x14)
#define GPIOB_LCKR	*(vint32_t*) (GPIOB_BASE + 0x18)
#define GPIOB_ODR	*(vint32_t*) (GPIOB_BASE + 0x0C)

void Clock_init();
void GPIO_init();

int main(void)
{
	unsigned volatile  int i = 0 ;
	//Adjusting Prescaler AHB
	RCC_CFGR |= (0b0000 << 4); // -> NO Prescaler

	//Adjusting Prescaler APB1
	RCC_CFGR |= (0b100 << 8); // ->  Prescaler/2



	//Adjusting Prescaler APB2
	RCC_CFGR |= (0b101 << 11); // ->  Prescaler/2

	//Setting Internal Oscillator ON (8MHz) to be SYSCLK
	RCC_CR |= (1 << 0) ; // -> HSI ON
	RCC_CFGR |= (0b00 << 0); // -> HSI Selected


	Clock_init();
	GPIO_init();


	while(1)
	{
		//PA1 >> PUR (connected to vcc)
		if( ((GPIOA_IDR & (1<<1)) >> 1) == 0 ) // press
		{
			GPIOB_ODR ^=  1<<1;
			while(( ((GPIOA_IDR & (1<<1)) >> 1) == 0) ); //Single Press
		}

		//PA13 >> PDR (connected to ground)
		if( ((GPIOA_IDR & (1<<13)) >> 13) == 1 ) // press
		{
			GPIOB_ODR ^= 1<<13; // Multi Press

		}
	}

	for(i ; i <512 ; i++);

	return 0;
}
void Clock_init()
{
	RCC_APB2ENR |= RCC_IOPAEN;
	RCC_APB2ENR |= RCC_IOPBEN;

}
void GPIO_init()
{
	GPIOA_CRL = 0x0 ;
	GPIOB_CRL = 0x0 ;
	GPIOA_CRH = 0x0 ;


	//PA1 input HighZ
	GPIOA_CRL |= (1 << 6);

	//PA13 input HighZ
	GPIOA_CRH &= ~(0b11 << 20);
	GPIOA_CRH |= (0b01 << 22);

	//PB1 Output push pull mode
	GPIOB_CRL &= ~(0b11 << 6);
	GPIOB_CRL |= (0b01 << 4);

	//PB13 Output push pull mode
	GPIOB_CRH &= ~(0b11 << 22);
	GPIOB_CRH |= (0b01 << 20);



}
